apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
spec:
  minAvailable: {{ .Values.spec.minAvailable}}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      version: {{ .Values.labels.version }}