apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appname }}-v1
  labels:
    version: {{ .Values.labels.version }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appname }}-v1
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.autoscaling.name }}
      target:
        type: {{ .Values.autoscaling.type }}
        averageUtilization: {{ .Values.autoscaling.averageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: {{ .Values.autoscaling.type }}
        averageUtilization: {{ .Values.autoscaling.averageUtilization }}