apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-v1
  labels:
    version: {{ .Values.labels.version }}
spec:
  minAvailable: {{ .Values.spec.minAvailable }}
  selector:
    matchLabels:
      version: {{ .Values.labels.version }}